spring.application.name=musicform
server.port=${PORT:8088}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/musicform}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2006}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.ru.itis.musicform=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

freesound.api.key=layPFe2I4iPelLinHtIq0fPm6lauk7uA4MJvjdGC
freesound.base.url=https://freesound.org/apiv2

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp